name: UiPath Orchestrator Credential Stores Get By Id
description: |
  NAME:
     uipath orchestrator credential-stores get-by-id - Gets a single Credential Store by its key.

  USAGE:
     uipath orchestrator credential-stores get-by-id [command options] [arguments...]

  DESCRIPTION:
     OAuth required scopes: OR.Settings or OR.Settings.Read.

     Required permissions: Settings.View.

  OPTIONS:
     --key integer (required)

     --expand string
        Indicates the related entities to be represented inline. The maximum depth is 2.

     --select string
        Limits the properties returned in the result.

on:
  workflow_call:
    inputs:
      key:
        description: 'The unique identifier key of the Credential Store (required).'
        required: true
        type: number
      expand:
        description: 'Related entities to be represented inline (optional, max depth 2).'
        required: false
        type: string
        default: ''
      select:
        description: 'Limits the properties returned in the result (optional).'
        required: false
        type: string
        default: ''

jobs:
  run-command:
    runs-on: [windows, self-hosted]
    steps:
      - name: Run uipath orchestrator credential-stores get-by-id command
        shell: pwsh
        run: |
          # Initialize the arguments array for the CLI command
          $args = @()

          # Append the base command
          $args += 'orchestrator'
          $args += 'credential-stores'
          $args += 'get-by-id'

          # Required argument --key
          $args += '--key'
          $args += "${{ inputs.key }}"

          # Append --expand if provided and not empty
          if ("${{ inputs.expand }}" -ne '') {
            $args += '--expand'
            $args += "${{ inputs.expand }}"
          }

          # Append --select if provided and not empty
          if ("${{ inputs.select }}" -ne '') {
            $args += '--select'
            $args += "${{ inputs.select }}"
          }

          # Execute the constructed CLI command
          uipath @args