name: 'UiPath Orchestrator Test Set Schedules Delete By Id'
description: |
  NAME:
     uipath orchestrator test-set-schedules delete-by-id - Delete an existing test set execution schedule

  USAGE:
     uipath orchestrator test-set-schedules delete-by-id [command options] [arguments...]

  DESCRIPTION:
     OAuth required scopes: OR.TestSetSchedules or OR.TestSetSchedules.Write.

     Required permissions: TestSetSchedules.Delete.

     Responses:
     204 The test set execution schedule was deleted
     403 If the caller doesn't have permissions to delete test set execution schedules

  OPTIONS:
     --folder-id integer (required)
        Folder/OrganizationUnit Id

     --key integer (required)
        ID of the test set execution schedule to be deleted

on:
  workflow_call:
    inputs:
      folder_id:
        required: true
        type: number
        description: 'Folder/OrganizationUnit Id (required)'
      key:
        required: true
        type: number
        description: 'ID of the test set execution schedule to be deleted (required)'

jobs:
  delete-schedule:
    runs-on: [windows, self-hosted]
    outputs: {}
    steps:
      - name: Run uipath orchestrator test-set-schedules delete-by-id
        shell: pwsh
        run: |
          # Initialize arguments array for CLI command
          $args = @()

          # Add required parameters
          $args += '--folder-id'
          $args += ${{ inputs.folder_id }}

          $args += '--key'
          $args += ${{ inputs.key }}

          # Execute the CLI command
          uipath orchestrator test-set-schedules delete-by-id @args