//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yash.Utility.Activities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yash.Utility.Activities.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Set.
        /// </summary>
        internal static string CreateExcelFile_DataSet_DisplayName {
            get {
                return ResourceManager.GetString("CreateExcelFile_DataSet_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSet containing DataTables to export as sheets (use this OR Data Table).
        /// </summary>
        internal static string CreateExcelFile_DataSet_Tooltip {
            get {
                return ResourceManager.GetString("CreateExcelFile_DataSet_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Table.
        /// </summary>
        internal static string CreateExcelFile_DataTable_DisplayName {
            get {
                return ResourceManager.GetString("CreateExcelFile_DataTable_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single DataTable to export (use this OR Data Set).
        /// </summary>
        internal static string CreateExcelFile_DataTable_Tooltip {
            get {
                return ResourceManager.GetString("CreateExcelFile_DataTable_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates an Excel file from a DataSet or DataTable. Each DataTable becomes a separate worksheet in the Excel file..
        /// </summary>
        internal static string CreateExcelFile_Description {
            get {
                return ResourceManager.GetString("CreateExcelFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Excel File.
        /// </summary>
        internal static string CreateExcelFile_DisplayName {
            get {
                return ResourceManager.GetString("CreateExcelFile_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Logging.
        /// </summary>
        internal static string CreateExcelFile_EnableLogging_DisplayName {
            get {
                return ResourceManager.GetString("CreateExcelFile_EnableLogging_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable detailed logging of the creation operation.
        /// </summary>
        internal static string CreateExcelFile_EnableLogging_Tooltip {
            get {
                return ResourceManager.GetString("CreateExcelFile_EnableLogging_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output File Path.
        /// </summary>
        internal static string CreateExcelFile_OutputPath_DisplayName {
            get {
                return ResourceManager.GetString("CreateExcelFile_OutputPath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path where the Excel file will be saved (.xlsx).
        /// </summary>
        internal static string CreateExcelFile_OutputPath_Tooltip {
            get {
                return ResourceManager.GetString("CreateExcelFile_OutputPath_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite Existing.
        /// </summary>
        internal static string CreateExcelFile_OverwriteExisting_DisplayName {
            get {
                return ResourceManager.GetString("CreateExcelFile_OverwriteExisting_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite existing file if it exists.
        /// </summary>
        internal static string CreateExcelFile_OverwriteExisting_Tooltip {
            get {
                return ResourceManager.GetString("CreateExcelFile_OverwriteExisting_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Name.
        /// </summary>
        internal static string CreateExcelFile_SheetName_DisplayName {
            get {
                return ResourceManager.GetString("CreateExcelFile_SheetName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional sheet name when using Data Table input.
        /// </summary>
        internal static string CreateExcelFile_SheetName_Tooltip {
            get {
                return ResourceManager.GetString("CreateExcelFile_SheetName_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reads an Excel file and converts its sheets into a DataSet. Uses EPPlus which can read files even when they are open in Excel..
        /// </summary>
        internal static string ReadExcelFile_Description {
            get {
                return ResourceManager.GetString("ReadExcelFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Excel File.
        /// </summary>
        internal static string ReadExcelFile_DisplayName {
            get {
                return ResourceManager.GetString("ReadExcelFile_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Logging.
        /// </summary>
        internal static string ReadExcelFile_EnableLogging_DisplayName {
            get {
                return ResourceManager.GetString("ReadExcelFile_EnableLogging_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable detailed logging of the read operation.
        /// </summary>
        internal static string ReadExcelFile_EnableLogging_Tooltip {
            get {
                return ResourceManager.GetString("ReadExcelFile_EnableLogging_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel File Path.
        /// </summary>
        internal static string ReadExcelFile_FilePath_DisplayName {
            get {
                return ResourceManager.GetString("ReadExcelFile_FilePath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the Excel workbook file (.xls or .xlsx).
        /// </summary>
        internal static string ReadExcelFile_FilePath_Tooltip {
            get {
                return ResourceManager.GetString("ReadExcelFile_FilePath_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSet Result.
        /// </summary>
        internal static string ReadExcelFile_Result_DisplayName {
            get {
                return ResourceManager.GetString("ReadExcelFile_Result_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSet containing all sheets as DataTables.
        /// </summary>
        internal static string ReadExcelFile_Result_Tooltip {
            get {
                return ResourceManager.GetString("ReadExcelFile_Result_Tooltip", resourceCulture);
            }
        }
    }
}
