name: Update Latest Package Version Bulk

description: |
  NAME:
     uipath orchestrator releases update-to-latest-package-version-bulk - Updates the package versions for the given releases to the latest available.

  USAGE:
     uipath orchestrator releases update-to-latest-package-version-bulk [command options] [arguments...]

  DESCRIPTION:
     OAuth required scopes: OR.Execution or OR.Execution.Write.

     Required permissions: Processes.Edit.

  OPTIONS:
     --folder-id integer (required)
        Folder/OrganizationUnit Id

     --release-ids integer,integer,... (required)

     --expand string
        Indicates the related entities to be represented inline. The maximum depth is 2.

     --merge-package-tags boolean

     --select string
        Limits the properties returned in the result.

on:
  workflow_call:
    inputs:
      folder-id:
        description: 'Folder/OrganizationUnit Id (required)'
        required: true
        type: number
      release-ids:
        description: 'Comma separated list of release ids (required)'
        required: true
        type: string
      expand:
        description: 'Related entities to be represented inline (optional)'
        required: false
        type: string
        default: ''
      merge-package-tags:
        description: 'Merge package tags flag (optional)'
        required: false
        type: boolean
        default: false
      select:
        description: 'Limits the properties returned in the result (optional)'
        required: false
        type: string
        default: ''

jobs:
  update-latest-package-version-bulk:
    runs-on: [windows, self-hosted]
    steps:
      - name: Build and run UiPath CLI command
        shell: pwsh
        run: |
          # Initialize args array for CLI parameters
          $args = @(
            "orchestrator", "releases", "update-to-latest-package-version-bulk"
            "--folder-id", "$(${{ inputs.folder-id }})"
            "--release-ids", "$(${{ inputs.release-ids }})"
          )

          # Add optional --expand if provided
          if ([string]::IsNullOrEmpty("${{ inputs.expand }}") -eq $false) {
            $args += '--expand'
            $args += "${{ inputs.expand }}"
          }

          # Add optional --merge-package-tags if true
          if (${{ inputs.'merge-package-tags' }}) {
            $args += '--merge-package-tags'
            $args += 'true'
          }

          # Add optional --select if provided
          if ([string]::IsNullOrEmpty("${{ inputs.select }}") -eq $false) {
            $args += '--select'
            $args += "${{ inputs.select }}"
          }

          # Run the uipath CLI with constructed arguments
          uipath @args
