//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yash.Config.Activities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yash.Config.Activities.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Url.
        /// </summary>
        internal static string LoadConfig_BaseUrl_DisplayName {
            get {
                return ResourceManager.GetString("LoadConfig_BaseUrl_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url ending at .uipath.com.
        /// </summary>
        internal static string LoadConfig_BaseUrl_Tooltip {
            get {
                return ResourceManager.GetString("LoadConfig_BaseUrl_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Id.
        /// </summary>
        internal static string LoadConfig_ClientId_DisplayName {
            get {
                return ResourceManager.GetString("LoadConfig_ClientId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LoadConfig_ClientId_Tooltip {
            get {
                return ResourceManager.GetString("LoadConfig_ClientId_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientSecret.
        /// </summary>
        internal static string LoadConfig_ClientSecret_DisplayName {
            get {
                return ResourceManager.GetString("LoadConfig_ClientSecret_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LoadConfig_ClientSecret_Tooltip {
            get {
                return ResourceManager.GetString("LoadConfig_ClientSecret_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Type.
        /// </summary>
        internal static string LoadConfig_ConfigType_DisplayName {
            get {
                return ResourceManager.GetString("LoadConfig_ConfigType_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fully typed config type. Use auto-generated classes..
        /// </summary>
        internal static string LoadConfig_ConfigType_Tooltip {
            get {
                return ResourceManager.GetString("LoadConfig_ConfigType_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a config file into a dictionary of strings and objects. Ideal use case is to pass that to a multiple assign, where the right-hand value is &apos;ConfigFactory.FromDictionary&lt;YOURCONFIGTYPE&gt;(DICTIONARYOUTPUT).
        /// </summary>
        internal static string LoadConfig_Description {
            get {
                return ResourceManager.GetString("LoadConfig_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Config.
        /// </summary>
        internal static string LoadConfig_DisplayName {
            get {
                return ResourceManager.GetString("LoadConfig_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Dictionary.
        /// </summary>
        internal static string LoadConfig_Result_DisplayName {
            get {
                return ResourceManager.GetString("LoadConfig_Result_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parsed dictionary of configurations..
        /// </summary>
        internal static string LoadConfig_Result_Tooltip {
            get {
                return ResourceManager.GetString("LoadConfig_Result_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scopes.
        /// </summary>
        internal static string LoadConfig_Scope_DisplayName {
            get {
                return ResourceManager.GetString("LoadConfig_Scope_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scopes to load from the config file.
        /// </summary>
        internal static string LoadConfig_Scope_Tooltip {
            get {
                return ResourceManager.GetString("LoadConfig_Scope_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Path.
        /// </summary>
        internal static string LoadConfig_WorkflowPath_DisplayName {
            get {
                return ResourceManager.GetString("LoadConfig_WorkflowPath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the config file to read..
        /// </summary>
        internal static string LoadConfig_WorkflowPath_Tooltip {
            get {
                return ResourceManager.GetString("LoadConfig_WorkflowPath_Tooltip", resourceCulture);
            }
        }
    }
}
