name: uipath-orchestrator-task-definitions-update-task-definition-by-id
description: |
  NAME:
     uipath orchestrator task-definitions update-task-definition-by-id - Updates Task Definition.

  USAGE:
     uipath orchestrator task-definitions update-task-definition-by-id [command options] [arguments...]

  DESCRIPTION:
     OAuth required scopes: OR.Tasks or OR.Tasks.Write.

     Required permissions: ActionDesign.Edit.

  OPTIONS:
     --key integer (required)
        Key of the object

     --description string
        Description of this task definition.

     --name string
        Name of the Task Definition.

     --properties object

        Example:
           allowedActions=string,string,...; schema=string
on:
  workflow_call:
    inputs:
      key:
        description: 'Key of the object (required)'
        required: true
        type: number
      description:
        description: 'Description of this task definition (optional)'
        required: false
        type: string
        default: ''
      name:
        description: 'Name of the Task Definition (optional)'
        required: false
        type: string
        default: ''
      properties:
        description: 'Properties string, e.g. allowedActions=string,string,...; schema=string (optional)'
        required: false
        type: string
        default: ''
jobs:
  update-task-definition:
    runs-on: [windows, self-hosted]
    name: Update UiPath Orchestrator Task Definition by ID
    steps:
      - name: Run update-task-definition-by-id command
        shell: pwsh
        env:
          # environment variables if needed (none specified)
        run: |
          # Construct the command arguments array
          $argsList = @()
          $argsList += 'orchestrator'
          $argsList += 'task-definitions'
          $argsList += 'update-task-definition-by-id'
          
          # Add required key argument
          $argsList += "--key"
          $argsList += "${{ inputs.key }}"
          
          # Conditionally add optional description if provided
          if ('${{ inputs.description }}' -ne '') {
              $argsList += "--description"
              $argsList += "${{ inputs.description }}"
          }
          # Conditionally add optional name if provided
          if ('${{ inputs.name }}' -ne '') {
              $argsList += "--name"
              $argsList += "${{ inputs.name }}"
          }
          # Conditionally add optional properties if provided
          if ('${{ inputs.properties }}' -ne '') {
              $argsList += "--properties"
              $argsList += "${{ inputs.properties }}"
          }

          # Join and invoke the uipath CLI command with proper quoting to handle spaces
          # Use & to run the command as executable, assuming 'uipath' is on PATH
          & uipath @argsList
