name: 'UiPath Orchestrator Environments Get Robot Ids For Environment By Key'
description: |
  NAME:
     uipath orchestrator environments get-robot-ids-for-environment-by-key - Returns a collection of all the ids of the robots associated to an environment based on environment Id.

  USAGE:
     uipath orchestrator environments get-robot-ids-for-environment-by-key [command options] [arguments...]

  DESCRIPTION:
     OAuth required scopes: OR.Robots or OR.Robots.Read.

     Required permissions: Environments.View and Robots.View.

  OPTIONS:
     --folder-id integer (required)
        Folder/OrganizationUnit Id

     --key integer (required)
        The Id of the environment for which the robot ids are fetched.

     --count boolean
        Indicates whether the total count of items within a collection are returned in the result.

     --expand string
        Indicates the related entities to be represented inline. The maximum depth is 2.

     --filter string
        Restricts the set of items returned. The maximum number of expressions is 100.

     --orderby string
        Specifies the order in which items are returned. The maximum number of expressions is 5.

     --select string
        Limits the properties returned in the result.

on:
  workflow_call:
    inputs:
      folder_id:
        description: 'Folder/OrganizationUnit Id (required)'
        required: true
        type: integer
      key:
        description: 'The Id of the environment for which the robot ids are fetched (required)'
        required: true
        type: integer
      count:
        description: 'Return total count of items within the collection (optional)'
        required: false
        type: boolean
        default: false
      expand:
        description: 'Related entities to represent inline, max depth 2 (optional)'
        required: false
        type: string
        default: ''
      filter:
        description: 'Restricts the set of returned items, max 100 expressions (optional)'
        required: false
        type: string
        default: ''
      orderby:
        description: 'Specifies order of returned items, max 5 expressions (optional)'
        required: false
        type: string
        default: ''
      select:
        description: 'Limits the properties returned in the result (optional)'
        required: false
        type: string
        default: ''

jobs:
  call-uipath-command:
    runs-on: [windows, self-hosted]
    outputs:
      exit-code: ${{ steps.run-command.outcome }}
    steps:
      - name: Run UiPath Orchestrator CLI Command
        id: run-command
        shell: pwsh
        run: |
          # Construct argument list for uipath CLI command
          $args = @('orchestrator', 'environments', 'get-robot-ids-for-environment-by-key')

          # Required parameters
          $args += '--folder-id'
          $args += "${{ inputs.folder_id }}"

          $args += '--key'
          $args += "${{ inputs.key }}"

          # Optional parameters - only add if provided and valid

          if (${{ inputs.count }}) {
            $args += '--count'
          }

          if (${{ inputs.expand }} -and ${{ inputs.expand }} -ne '') {
            $args += '--expand'
            $args += "${{ inputs.expand }}"
          }

          if (${{ inputs.filter }} -and ${{ inputs.filter }} -ne '') {
            $args += '--filter'
            $args += "${{ inputs.filter }}"
          }

          if (${{ inputs.orderby }} -and ${{ inputs.orderby }} -ne '') {
            $args += '--orderby'
            $args += "${{ inputs.orderby }}"
          }

          if (${{ inputs.select }} -and ${{ inputs.select }} -ne '') {
            $args += '--select'
            $args += "${{ inputs.select }}"
          }

          # Join and execute the command
          $escapedArgs = $args | ForEach-Object { ('"{0}"' -f ($_ -replace '"', '\"')) }
          $command = "uipath " + ($escapedArgs -join ' ')
          Write-Host "Running command: $command"

          & uipath @args
          exit $LASTEXITCODE