name: 'uipath-orchestrator-sessions-delete-inactive-unattended-sessions'
description: |
  NAME:
     uipath orchestrator sessions delete-inactive-unattended-sessions - Deletes disconnected or unresponsive sessions

  USAGE:
     uipath orchestrator sessions delete-inactive-unattended-sessions [command options] [arguments...]

  DESCRIPTION:
     OAuth required scopes: OR.Robots or OR.Robots.Write.

     Required permissions: Robots.Delete.

  OPTIONS:
     --session-ids integer,integer,...
  
on:
  workflow_call:
    inputs:
      session_ids:
        description: 'Comma separated list of session IDs to delete'
        required: false
        type: string

jobs:
  delete_inactive_unattended_sessions:
    runs-on: [windows, self-hosted]
    steps:
      - name: Run uipath orchestrator sessions delete-inactive-unattended-sessions
        shell: pwsh
        run: |
          $args = @("orchestrator", "sessions", "delete-inactive-unattended-sessions")

          if ('${{ inputs.session_ids }}' -and '${{ inputs.session_ids }}'.Trim().Length -gt 0) {
            $args += "--session-ids"
            $args += "'${{ inputs.session_ids }}'"
          }

          Write-Host "Executing: uipath $($args -join ' ')"
          & uipath @args