using System;
using Yash.Config.Models;

// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Yash.Config GenerateConfigClass wizard on 08-09-2025 01:42:09.
//
//     Changes to this file may be overwritten if the tool is rerun.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace Finance.Automations.Configs
{
	public class Config : Yash.Config.Models.Config
	{

		#region Settings

		/// <summary>
		/// The end of a maintenance window.
		/// </summary>
		public TimeSpan Maintenance_End { get; set; }

		#endregion
	}
}
