name: uipath-orchestrator-credential-stores-get-available-credential-store-types
description: |-
  NAME:
     uipath orchestrator credential-stores get-available-credential-store-types - Gets available Credential Store types.

  USAGE:
     uipath orchestrator credential-stores get-available-credential-store-types [command options] [arguments...]

  DESCRIPTION:
     OAuth required scopes: OR.Settings or OR.Settings.Read.

     Required permissions: Settings.View.

  OPTIONS:
     --count boolean
        Indicates whether the total count of items within a collection are returned in the result.

     --expand string
        Indicates the related entities to be represented inline. The maximum depth is 2.

     --filter string
        Restricts the set of items returned. The maximum number of expressions is 100.

     --orderby string
        Specifies the order in which items are returned. The maximum number of expressions is 5.

     --proxy-id integer

     --select string
        Limits the properties returned in the result.
on:
  workflow_call:
    inputs:
      count:
        description: Indicates whether to return the total count of items within the collection.
        required: false
        type: boolean
        default: false
      expand:
        description: Indicates the related entities to be represented inline. Max depth 2.
        required: false
        type: string
        default: ''
      filter:
        description: Restricts the set of items returned. Max expressions 100.
        required: false
        type: string
        default: ''
      orderby:
        description: Specifies the order in which items are returned. Max expressions 5.
        required: false
        type: string
        default: ''
      proxy_id:
        description: Proxy ID as integer.
        required: false
        type: int
        default: 0
      select:
        description: Limits the properties returned in the result.
        required: false
        type: string
        default: ''
jobs:
  run-cli:
    runs-on:
      - windows
      - self-hosted
    outputs: {}
    steps:
      - name: Run UiPath Orchestrator Credential Stores Get Available Credential Store Types
        shell: pwsh
        run: |
          $args = @('orchestrator', 'credential-stores', 'get-available-credential-store-types')

          # Append --count if true
          if (${{ inputs.count }}) {
            $args += '--count'
            $args += 'true'
          }

          # Append --expand if provided a non-empty string
          if (${{ inputs.expand }} -ne '') {
            $args += '--expand'
            $args += "${{ inputs.expand }}"
          }

          # Append --filter if provided a non-empty string
          if (${{ inputs.filter }} -ne '') {
            $args += '--filter'
            $args += "${{ inputs.filter }}"
          }

          # Append --orderby if provided a non-empty string
          if (${{ inputs.orderby }} -ne '') {
            $args += '--orderby'
            $args += "${{ inputs.orderby }}"
          }

          # Append --proxy-id if provided and > 0
          if (${{ inputs.proxy_id }} -gt 0) {
            $args += '--proxy-id'
            $args += "${{ inputs.proxy_id }}"
          }

          # Append --select if provided a non-empty string
          if (${{ inputs.select }} -ne '') {
            $args += '--select'
            $args += "${{ inputs.select }}"
          }

          # Combine and run the command
          $command = 'uipath ' + ($args -join ' ')
          Write-Host "Running command: $command"
          iex $command