name: UiPath Orchestrator Get Task Data By ID
description: |
  NAME:
     uipath orchestrator task-forms get-task-data-by-id - Returns task data dto

  USAGE:
     uipath orchestrator task-forms get-task-data-by-id [command options] [arguments...]

  DESCRIPTION:
     OAuth required scopes: OR.Tasks or OR.Tasks.Read.

     Required permissions: Tasks.View.

  OPTIONS:
     --folder-id integer (required)
        Folder/OrganizationUnit Id

     --task-id integer
        Task id

on:
  workflow_call:
    inputs:
      folder-id:
        description: Folder/OrganizationUnit Id (required)
        required: true
        type: integer
      task-id:
        description: Task id (optional)
        required: false
        type: integer

jobs:
  run-task-forms-get-task-data-by-id:
    runs-on: [windows, self-hosted]
    steps:
      - name: Run uipath orchestrator task-forms get-task-data-by-id
        shell: pwsh
        run: |
          $args = @("orchestrator", "task-forms", "get-task-data-by-id")

          # Add required --folder-id argument
          $args += "--folder-id"
          $args += "${{ inputs.folder-id }}"

          # Add optional --task-id argument if provided
          if (${{ inputs.task-id }}) {
              $args += "--task-id"
              $args += "${{ inputs.task-id }}"
          }

          # Invoke the CLI command with constructed arguments
          Write-Host "Running command: uipath $($args -join ' ')"
          uipath @args