name: 'Publish to UiPath Orchestrator'
description: 'Publishes UiPath packages to Orchestrator using modern UiPath CLI'
inputs:
  package-path:
    description: 'Path to the .nupkg file to publish'
    required: true
  orchestrator-url:
    description: 'The URL of the Orchestrator instance'
    required: true
  orchestrator-tenant:
    description: 'The tenant of the Orchestrator instance'
    required: true
  account-name:
    description: 'The Orchestrator organization name'
    required: true
  application-id:
    description: 'The external application id for authentication'
    required: true
  application-secret:
    description: 'The external application secret for authentication'
    required: true
  application-scope:
    description: 'The space-separated list of application scopes'
    required: false
    default: 'OR.Administration OR.Analytics OR.Assets OR.Audit OR.AutomationSolutions.Access OR.Execution OR.Folders OR.Hypervisor OR.Jobs OR.License OR.Machines OR.ML OR.Monitoring OR.Queues OR.Robots OR.Settings OR.Tasks OR.TestDataQueues OR.TestSetExecutions OR.TestSets OR.TestSetSchedules OR.Users OR.Webhooks OR.BackgroundTasks'
runs:
  using: 'node20'
  main: 'index.js'
