name: Delete all items from a UiPath test data queue
description: |
  NAME:
     uipath orchestrator test-data-queue-actions delete-all-items - Delete all items from a test data queue

  USAGE:
     uipath orchestrator test-data-queue-actions delete-all-items [command options] [arguments...]

  DESCRIPTION:
     OAuth required scopes: OR.TestDataQueues or OR.TestDataQueues.Write.

     Required permissions: TestDataQueueItems.Delete.

     Responses:
     202 All items from the test data queue were scheduled for deletion
     403 If the caller doesn't have permissions to delete test data queue items

  OPTIONS:
     --folder-id integer (required)
        Folder/OrganizationUnit Id

     --queue-name string
        The name of the test data queue

on:
  workflow_call:
    inputs:
      folder_id:
        description: Folder/OrganizationUnit Id
        required: true
        type: number
      queue_name:
        description: The name of the test data queue (optional)
        required: false
        type: string

jobs:
  delete_all_items:
    runs-on: [windows, self-hosted]
    outputs: {}
    steps:
      - name: Run uipath delete-all-items command
        shell: pwsh
        run: |
          # Initialize argument array
          $args = @()

          # Required folder-id argument
          $args += '--folder-id'
          $args += ${{ inputs.folder_id }}

          # Optional queue-name argument
          if ("${{ inputs.queue_name }}" -ne "") {
            $args += '--queue-name'
            $args += "${{ inputs.queue_name }}"
          }

          # Execute the uipath CLI with orchestrator test-data-queue-actions delete-all-items command and arguments
          uipath orchestrator test-data-queue-actions delete-all-items @args | Write-Host