using System;
using Yash.Config.Models;
using System.Collections.Generic;
using System;
using System.Collections.Generic;

// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Yash.Config GenerateConfigClass wizard on 10-09-2025 21:11:04.
//
//     Changes to this file may be overwritten if the tool is rerun.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace Yash.StandardProject.Configs
{
	public class PerformerConfig : Yash.Config.Models.Config
	{

		#region Settings

		/// <summary>
		/// The name of the process to be used for logging and reporting purposes.
		/// </summary>
		public string ProcessName { get; set; }

		/// <summary>
		/// The processes to kill before executing the process.
		/// </summary>
		public List<string> ProcessesToKill { get; set; }

		#endregion
	}
}
