using System;
using Yash.Config.Models;
using System;
using System.Collections.Generic;

// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Yash.Config GenerateConfigClass wizard on 10-09-2025 21:11:04.
//
//     Changes to this file may be overwritten if the tool is rerun.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace Yash.StandardProject.Configs
{
	public class ReporterConfig : Yash.Config.Models.Config
	{

		#region Settings

		/// <summary>
		/// The name of the process to be used for logging and reporting purposes.
		/// </summary>
		public string ProcessName { get; set; }

		/// <summary>
		/// The path to the template for the report.
		/// </summary>
		public string TemplatePath { get; set; }

		/// <summary>
		/// The sheet to populate with the data from the queue.
		/// </summary>
		public string TemplateSheet { get; set; }

		/// <summary>
		/// The path to the temp folder for storing reports temporarily.
		/// </summary>
		public string Folder_Temp { get; set; }

		/// <summary>
		/// The statuses to report out. Must match the QueueStatuses enum values and be in a CSV.
		/// </summary>
		public string StatusesToReport { get; set; }

		/// <summary>
		/// The amount of time saved per successful transaction (hrs).
		/// </summary>
		public double TimeSaved_Success { get; set; }

		/// <summary>
		/// The amount of time saved per system exception (hrs).
		/// </summary>
		public double TimeSaved_SysEx { get; set; }

		/// <summary>
		/// The amount of time saved per business exception (hrs).
		/// </summary>
		public double TimeSaved_BusEx { get; set; }

		#endregion

		#region Assets
		public string Report_To { get; set; }

		#endregion
	}
}
