using System;
using Yash.Config.Models;
using System;
using System.Collections.Generic;

// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Yash.Config GenerateConfigClass wizard on 10-09-2025 21:11:04.
//
//     Changes to this file may be overwritten if the tool is rerun.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace Yash.StandardProject.Configs
{
	public class SharedConfig : Yash.Config.Models.Config
	{

		#region Settings

		/// <summary>
		/// The name of the queue to add items to.
		/// </summary>
		public string QueueName { get; set; }

		/// <summary>
		/// The folder of the queue to add items to.
		/// </summary>
		public string QueueFolder { get; set; }

		/// <summary>
		/// The folder to save the exception screenshots of the process.
		/// </summary>
		public string Folder_ExScreenshots { get; set; }

		/// <summary>
		/// The start of a maintenance window.
		/// </summary>
		public TimeSpan Maintenance_Start { get; set; }

		/// <summary>
		/// The end of a maintenance window.
		/// </summary>
		public TimeSpan Maintenance_End { get; set; }

		/// <summary>
		/// The maximum consecutive exceptions before stopping the processing.
		/// </summary>
		public int MaxConsecutiveExceptions { get; set; }

		#endregion

		#region Assets
		public string SysEx_To { get; set; }
		public string BusEx_To { get; set; }
		public string Report_To { get; set; }

		#endregion

		#region Files
		public string Email_SysEx { get; set; }
		public string Email_BusEx { get; set; }
		public string Email_Report { get; set; }
		public string Email_FrameEx { get; set; }

		#endregion
	}
}
