using System;
using Yash.Config.Models;
using System;
using System.Collections.Generic;

// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Yash.Config GenerateConfigClass wizard on 25-07-2025 11:08:34.
//
//     Changes to this file may be overwritten if the tool is rerun.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace Yash.Config.StudioTestProject.Models.Configs
{
	public class Config : Yash.Config.Models.Config
	{
	}
}
