using System;
using Yash.Config.Models;
using System;
using System.Collections.Generic;

// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Yash.Config GenerateConfigClass wizard on 05-09-2025 12:33:05.
//
//     Changes to this file may be overwritten if the tool is rerun.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace Yash.Config.StudioTestProject.Models.Configs
{
	public class SharedConfig : Yash.Config.Models.Config.Configuration
	{
		#region Settings

		/// <summary>
		/// Sample
		/// </summary>
		public string Key { get; set; }

		#endregion
	}
}
