name: 'Update Project Version'
description: 'Updates project version and package dependencies in UiPath project.json'
inputs:
  project-path:
    description: 'Path to the project folder containing project.json'
    required: false
    default: '.'
  version:
    description: 'Set specific project version (e.g., "25.10.0")'
    required: false
  major:
    description: 'Increment major version (X.0.0)'
    required: false
    default: 'false'
  minor:
    description: 'Increment minor version (X.Y.0)'
    required: false
    default: 'false'
  patch:
    description: 'Increment patch version (X.Y.Z)'
    required: false
    default: 'false'
  packages:
    description: 'Update packages (JSON array or newline-separated NAME:VERSION pairs)'
    required: false
  dry-run:
    description: 'Show what would be changed without making changes'
    required: false
    default: 'false'
  verbose:
    description: 'Show detailed processing information'
    required: false
    default: 'false'
  create-backup:
    description: 'Create backup file before making changes'
    required: false
    default: 'false'
outputs:
  old-version:
    description: 'The original project version'
  new-version:
    description: 'The updated project version'
  packages-updated:
    description: 'Number of packages updated'
  backup-file:
    description: 'Path to backup file (if created)'
runs:
  using: 'node20'
  main: 'index.js'