name: 'uipath orchestrator task-forms get-task-form-by-id'
description: |
  NAME:
     uipath orchestrator task-forms get-task-form-by-id - Returns form dto to render task form

  USAGE:
     uipath orchestrator task-forms get-task-form-by-id [command options] [arguments...]

  DESCRIPTION:
     OAuth required scopes: OR.Tasks or OR.Tasks.Read.

     Required permissions: Tasks.View.

  OPTIONS:
     --folder-id integer (required)
        Folder/OrganizationUnit Id

     --expand-on-form-layout boolean (default: false)

     --task-id integer
        Task id

on:
  workflow_call:
    inputs:
      folder_id:
        description: 'Folder/OrganizationUnit Id (required)'
        required: true
        type: number
      expand_on_form_layout:
        description: 'Expand on form layout (boolean, default: false)'
        required: false
        type: boolean
        default: false
      task_id:
        description: 'Task id (optional)'
        required: false
        type: number

jobs:
  get-task-form-by-id:
    runs-on: [windows, self-hosted]
    steps:
      - name: Run uipath orchestrator task-forms get-task-form-by-id command
        shell: pwsh
        run: |
          $args = @('orchestrator', 'task-forms', 'get-task-form-by-id')
          # Required folder-id argument
          $args += '--folder-id'
          $args += "$(${{ inputs.folder_id }})"

          # Optional expand-on-form-layout argument
          if (${{ inputs.expand_on_form_layout }}) {
            $args += '--expand-on-form-layout'
            $args += 'true'
          } else {
            # Only add if true, but default is false, so skip.
          }

          # Optional task-id argument
          if (${{ inputs.task_id }}) {
            $args += '--task-id'
            $args += "$(${{ inputs.task_id }})"
          }

          Write-Host "Running: uipath $args"
          uipath @args
