name: Build VS Project

on:
  workflow_call:
    inputs:
      id: { required: true, type: string }
      path: { required: true, type: string }
    secrets:
      nuget_api_key: { required: true }

jobs:
  compute-version:
    uses: ./.github/workflows/compute-version.yml
    with:
      id: ${{ inputs.id }}

  build:
    needs: compute-version
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v3
        with: { fetch-depth: 0 }

      - name: Build Project
        run: |
          cd ${{ inputs.path }}
          dotnet build -c Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.compute-version.outputs.full_version }}
          path: ${{ inputs.path }}/bin/Release/*.nupkg

  tag:
    needs: [build, compute-version]
    uses: ./.github/workflows/create-github-tag.yml
    with:
      id: ${{ inputs.id }}
      version: ${{ needs.compute-version.outputs.version }}
      full_version: ${{ needs.compute-version.outputs.full_version }}

  release:
    needs: [tag, build, compute-version]
    runs-on: [self-hosted, windows]
    steps:
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ needs.compute-version.outputs.full_version }}
          release_name: Release ${{ needs.compute-version.outputs.full_version }}
          draft: false
          prerelease: false

  publish-github:
    needs: [release, tag, build, compute-version]
    uses: ./.github/workflows/publish-to-GitHub.yml
    with:
      package_path: ${{ inputs.path }}/bin/Release/${{ needs.compute-version.outputs.full_version }}.nupkg
      repository_owner: ${{ github.repository_owner }}

  publish-nuget:
    needs: [release, tag, build, compute-version]
    uses: ./.github/workflows/publish-to-NuGet.yml
    with:
      nupkg_path: ${{ inputs.path }}/bin/Release/${{ needs.compute-version.outputs.full_version }}.nupkg
    secrets:
      nuget_api_key: ${{ secrets.nuget_api_key }}
