name: "Deploy"

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main

jobs:
  start:
    name: Package
    runs-on: self-hosted
    steps:
      - name: "Initialize"
        run: uipcli --version
