name: Build Changed Projects

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  initialize:
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v3

      - name: Configure Git for GitHub Actions
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

  detect:
    needs: initialize
    uses: ./.github/workflows/step-detect-changes.yml
    
  build:
    if: ${{ needs.detect.outputs.matrix != '{"include":[]}' }}
    needs: detect
    strategy:
      matrix: ${{ fromJson(needs.detect.outputs.matrix) }}
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v3

      - name: Build Project ${{ matrix.id }}
        uses: ./.github/workflows/project.yml
        with:
          id: ${{ matrix.id }}
          path: ${{ matrix.path }}
          type: ${{ matrix.type }}

  # build-uipath:
  #   needs: detect
  #   if: needs.detect.outputs.matrix != '{"include":[]}'
  #   runs-on: [self-hosted, windows]
  #   strategy:
  #     matrix: ${{ fromJson(needs.detect.outputs.matrix) }}
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Build UiPath Project ${{ matrix.id }}
  #       if: startsWith(matrix.type, 'uipath-')
  #       run: |
  #         echo "Packing UiPath project ${{ matrix.id }}"
  #         cd ${{ matrix.path }}
  #         uipcli pack --project-path .

  # build-vs:
  #   needs: detect
  #   if: needs.detect.outputs.matrix != '{"include":[]}'
  #   strategy:
  #     matrix: ${{ fromJson(needs.detect.outputs.matrix) }}
  #   uses: ./.github/workflows/vs-project.yml
  #   with:
  #     id: ${{ matrix.id }}
  #     path: ${{ matrix.path }}
  #   secrets: inherit
