name: Publish to NuGet

on:
  workflow_call:
    inputs:
      nupkg_path:
        required: true
        type: string
    secrets:
      nuget_api_key:
        required: true

jobs:
  publish:
    runs-on: [self-hosted, windows]
    steps:
      - name: Publish NuGet Package to nuget.org
        shell: powershell
        run: |
          $packagePath = "${{ inputs.nupkg_path }}"
          Write-Host "Pushing package to nuget.org: $packagePath"
          $apiKey = "${{ secrets.nuget_api_key }}"
          if (-not $apiKey) {
            Write-Error "NUGET_ORG_API_KEY is not set. Skipping nuget.org push."
            exit 1
          }
          dotnet nuget push @(
            "$packagePath",
            "--api-key", "${{ secrets.nuget_api_key }}",
            "--source", "https://api.nuget.org/v3/index.json",
            "--skip-duplicate"
          )
