name: Build Project

on:
  workflow_call:
    inputs:
      id:
        required: true
        type: string
      folder_path:
        required: true
        type: string
      full_version:
        required: true
        type: string
      version:
        required: true
        type: string
      type:
        required: false
        type: string
    outputs:
        artifact-id:
          value: ${{ jobs.build.outputs.artifact-id }}

jobs:
  build:
    runs-on: [self-hosted, windows]
    outputs:
      artifact-id: ${{ steps.upload-artifact.outputs.artifact-id }}
    steps:
      - uses: actions/checkout@v3
        with: { fetch-depth: 0 }

      - name: Restore, Build and Package Project
        if: ${{ startsWith(inputs.type, 'vs') }}
        shell: powershell
        id: build-vs
        run: |
          cd ${{ inputs.folder_path }}
          $csproj = Get-ChildItem *.csproj -Recurse | Select-Object -First 1
          if ($csproj -ne $null) {
            dotnet restore $csproj.FullName
            dotnet build $csproj.FullName --configuration Release
            dotnet pack $csproj.FullName --configuration Release -p:PackageVersion=${{ inputs.version }} --output ./
          } else {
            Write-Host "No .csproj found. Skipping."
            exit 1
          }
          "nuget_path=$version" >> $env:GITHUB_OUTPUT

      - name: Restore, Build and Package Project
        if: ${{ startsWith(inputs.type, 'uipath') }}
        shell: powershell
        id: build-uipath
        run: |
          echo "Packing UiPath project ${{ inputs.id }}"
          cd ${{ inputs.folder_path }}
          uipcli pack --project-path .
     
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.full_version }}
          path: ${{ inputs.folder_path }}/*.nupkg
        id: upload-artifact

      - name: Set Artifact Id Output
        run: |
            "artifact-id=${{ steps.upload-artifact.outputs.artifact-id }}" >> $env:GITHUB_OUTPUT

            Write-Host "Artifact Id: $artifact-id"