using System;
using Yash.Config.Models;
using System;
using System.Collections.Generic;

// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Yash.Config GenerateConfigClass wizard on 30-07-2025 08:27:19.
//
//     Changes to this file may be overwritten if the tool is rerun.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace Yash.Config.StudioTestProject.Models.Configs
{
	public class Config : Yash.Config.Models.Config
	{

		#region Settings

		/// <summary>
		/// Sample
		/// </summary>
		public string Key { get; set; }

		#endregion
	}
}
